# Generated by Django 5.1.11 on 2025-07-22 23:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DayReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.JSONField(default=dict)),
                (
                    "day",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="planner.day",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        default="My Month",
                        help_text="my awesome month",
                        max_length=50,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="when the month starts",
                    ),
                ),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_over", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_vaults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "unique_together": {("user", "start_date")},
            },
        ),
        migrations.CreateModel(
            name="MonthReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.JSONField(default=dict)),
                (
                    "monthly_vault",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="planner.monthlyvault",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "monthly_vault",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="planner.monthlyvault",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "unique_together": {("monthly_vault", "title")},
            },
        ),
        migrations.CreateModel(
            name="PlannedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "study_type",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("theory", "Theory 📚"),
                            ("coding", "Coding 💻"),
                            ("practice", "Practice 🔨"),
                            ("review", "Review 🔄"),
                            ("project", "Project 🏗️"),
                            ("research", "Research 🔬"),
                        ],
                        max_length=46,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Easy"),
                            (3, "Medium"),
                            (4, "Hard"),
                            (5, "Expert"),
                        ],
                        default=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_tasks",
                        to="planner.day",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)s_tasks", to="planner.subject"
                    ),
                ),
            ],
            options={
                "ordering": ["start_time", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActualTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "study_type",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("theory", "Theory 📚"),
                            ("coding", "Coding 💻"),
                            ("practice", "Practice 🔨"),
                            ("review", "Review 🔄"),
                            ("project", "Project 🏗️"),
                            ("research", "Research 🔬"),
                        ],
                        max_length=46,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Easy"),
                            (3, "Medium"),
                            (4, "Hard"),
                            (5, "Expert"),
                        ],
                        default=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "completion_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "quality_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "focus_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actual_tasks",
                        to="planner.day",
                    ),
                ),
                (
                    "planned_task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution",
                        to="planner.plannedtask",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)s_tasks", to="planner.subject"
                    ),
                ),
            ],
            options={
                "ordering": ["start_time", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "monthly_vault",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="planner.monthlyvault",
                    ),
                ),
            ],
            options={
                "ordering": ["monthly_vault", "week_number"],
            },
        ),
        migrations.AddField(
            model_name="day",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="planner.week",
            ),
        ),
        migrations.CreateModel(
            name="WeekReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.JSONField(default=dict)),
                (
                    "week",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="planner.week",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="a link to a github repo ,a website, or google drive folder",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(upload_to="projects/"),
                ),
                (
                    "monthly_vault",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="planner.monthlyvault",
                    ),
                ),
            ],
            options={
                "ordering": ["monthly_vault", "title"],
                "unique_together": {("monthly_vault", "title")},
            },
        ),
        migrations.AddIndex(
            model_name="plannedtask",
            index=models.Index(
                fields=["day", "start_time"], name="planner_pla_day_id_d291df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plannedtask",
            index=models.Index(
                fields=["day", "priority"], name="planner_pla_day_id_61bc40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actualtask",
            index=models.Index(
                fields=["day", "start_time"], name="planner_act_day_id_6807ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actualtask",
            index=models.Index(
                fields=["planned_task"], name="planner_act_planned_1cd8b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actualtask",
            index=models.Index(
                fields=["completion_percentage"], name="planner_act_complet_38528a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="week",
            unique_together={("monthly_vault", "week_number")},
        ),
        migrations.AlterUniqueTogether(
            name="day",
            unique_together={("user", "date"), ("week", "date")},
        ),
    ]
